/**
 * FailproofAI Integration for Pi Coding Agent
 * Generated by failproofai
 */
import { spawnSync } from "node:child_process";
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  const reportedSessions = new Set<string>();

  const callcli = (event: string, args: any, ctx?: any) => {
    // Session ID priority: 
    // 1. ctx.sessionId or ctx.session.id (SDK scoped)
    // 2. pi.session.id (Global scoped)
    // 3. Fallback to Project Name
    const projectName = process.cwd().split("/").pop() || "failproofai";
    // DIAGNOSTIC PROBE: Remove after ID is found
    try {
      if (!reportedSessions.has("dumped")) {
        const { writeFileSync } = require("node:fs");
        writeFileSync("/tmp/pi_dump.json", JSON.stringify({ 
          ctx_keys: Object.keys(ctx || {}),
          pi_session_keys: Object.keys(pi.session || {}),
          ctx_session: ctx?.session,
          pi_session: pi.session,
          pi_context: (pi as any).context
        }, null, 2));
        reportedSessions.add("dumped");
      }
    } catch {}

    const sessionId = ctx?.sessionId || ctx?.session?.id || pi.session?.id || pi.session?.sessionId || projectName;
    
    const payloadWithCwd = {
      ...args,
      integration: "pi",
      cwd: process.cwd(),
      session_id: sessionId,
    };

    const cmd = '"/home/yashu/.nvm/versions/node/v24.14.0/bin/node" "/home/yashu/fp/failproofai/dist/cli.mjs" --hook ' + event + ' --integration pi --stdin';

    const res = spawnSync(cmd, {
      input: JSON.stringify(payloadWithCwd),
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
      shell: true,
    });

    if (res.status !== 0) {
      const reason = res.stderr || res.stdout || "Action blocked by FailproofAI policy";
      // Use TUI status bar for premium feedback if possible
      if (ctx?.ui?.setStatus) {
        try { ctx.ui.setStatus("FailproofAI: Blocked - " + reason); } catch {}
      } else {
        try { (pi as any).log?.("FailproofAI: Blocked - " + reason); } catch {}
      }
      return { block: true, reason };
    }

    return { block: false };
  };

  pi.on("session_start", (event, ctx) => {
    try { callcli("SessionStart", {}, ctx); } catch {}
  });

  pi.on("tool_call", (event, ctx) => {
    try {
      const toolName = event.toolName || event.name;
      const toolInput = event.input || event.args || event.arguments;
      const res = callcli("PreToolUse", { 
        tool_name: toolName, 
        tool_input: toolInput 
      }, ctx);
      if (res?.block) return { block: true, reason: res.reason };
    } catch {}
  });

  pi.on("tool_result", (event, ctx) => {
    try {
      const toolName = event.toolName || event.name;
      const toolInput = event.input || event.args || event.arguments;
      const toolOutput = event.result?.content || event.output || event.result;
      callcli("PostToolUse", { 
        tool_name: toolName, 
        tool_input: toolInput,
        tool_output: toolOutput
      }, ctx);
    } catch {}
  });

  pi.on("input", (event, ctx) => {
    try {
      const text = event.text || event.input || event.content || (typeof event === "string" ? event : "");
      if (text) {
        // Isolation guard: ensure we don't handle messages that might be recursive
        if (text === "/failproofai-status") return;
        callcli("UserPromptSubmit", { tool_input: text }, ctx);
      }
    } catch {}
  });
}
