/**
 * FailproofAI Integration for OpenCode
 * Generated by failproofai
 */
import { spawnSync } from "node:child_process";

export const FailproofAIPlugin = (ctx: any) => {
  let currentSessionId: string | undefined;
  const reportedSessions = new Set<string>();

  const callcli = (event: string, args: any) => {
    const payloadWithCwd = {
      ...args,
      integration: "opencode",
      cwd: ctx.directory,
      session_id: args.session_id || currentSessionId,
    };

    const cmd = 'npx -y failproofai --hook ' + event + ' --integration opencode --stdin';

    const res = spawnSync(cmd, {
      input: JSON.stringify(payloadWithCwd),
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
      shell: true,
    });

    if (res.status !== 0) {
      throw new Error(res.stderr || res.stdout || "Action blocked by FailproofAI policy");
    }

    if (res.stdout) process.stdout.write(res.stdout);
    if (res.stderr) process.stderr.write(res.stderr);
  };

  const syncSession = (id: string) => {
    if (!id || reportedSessions.has(id)) return;
    reportedSessions.add(id);
    currentSessionId = id;
    try { callcli("SessionStart", { session_id: id }); } catch {}
  };

  return {
    "chat.message": async (input: any, output: any) => {
      try {
        if (input?.sessionID) syncSession(input.sessionID);
        const parts: any[] = output?.parts ?? [];
        const text = parts.find((p: any) => p.type === "text")?.text;
        if (text) callcli("UserPromptSubmit", { tool_input: text });
      } catch {}
    },
    "tool.execute.before": async (input: any, output: any) => {
      callcli("PreToolUse", { tool_name: input.tool, tool_input: output.args });
    },
    "tool.execute.after": async (input: any, output: any) => {
      try {
        callcli("PostToolUse", { tool_name: input.tool, tool_input: output.args, tool_output: output.result });
      } catch {}
    },
    "session.created": async (input: any) => {
      syncSession(input.sessionID);
    },
    "session.idle": async (input: any) => {
      try { callcli("SessionEnd", { session_id: input.sessionID }); } catch {}
    },
  };
};

export default FailproofAIPlugin;
