// AUTO-GENERATED by failproofai. __failproofai_hook__
// Re-generate via: failproofai policies --install --cli opencode
//
// DEV variant: this repo's contributors run failproofai from source via
// `bun bin/failproofai.mjs ...` instead of `npx -y failproofai`. This file
// is the project-scope shim with that dev path baked in. The production
// shape (npx-based) is generated by `src/hooks/integrations.ts` on install
// for end users — see `buildOpenCodePluginShim` there.
//
// Do NOT install this repo via `failproofai policies --install --cli
// opencode --scope project` — it would overwrite this dev path with the
// portable npx form.
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dirname, "..", "..");
const FAILPROOFAI_DEV_BIN = resolve(REPO_ROOT, "bin", "failproofai.mjs");

const BUS_EVENT_MAP = {
  "session.created": "SessionStart",
  "session.deleted": "SessionEnd",
  "session.idle":    "Stop",
};

function runFailproofai(eventName, payload, directory) {
  const r = spawnSync("bun", [FAILPROOFAI_DEV_BIN, "--hook", eventName, "--cli", "opencode"], {
    input: JSON.stringify(payload),
    encoding: "utf8",
    timeout: 60_000,
    cwd: directory,
  });
  return { exitCode: r.status ?? 0, stdout: r.stdout ?? "", stderr: r.stderr ?? "" };
}

function applyDecision(result, ctx) {
  if (result.exitCode === 2) {
    throw new Error((result.stderr || "").trim() || "Blocked by failproofai");
  }
  let parsed = null;
  try { parsed = JSON.parse(result.stdout); } catch { /* fail-open allow */ }
  if (!parsed) return;
  const out = parsed.hookSpecificOutput;
  if (out && out.permissionDecision === "deny") {
    throw new Error(out.permissionDecisionReason || "Blocked by failproofai");
  }
  if (out && out.decision && out.decision.behavior === "deny") {
    throw new Error((out.decision.message) || "Blocked by failproofai");
  }
  const ctxText = out && out.additionalContext;
  if (ctxText && ctx && ctx.client && ctx.sessionID) {
    Promise.resolve(ctx.client.session.prompt({
      path: { id: ctx.sessionID },
      body: { parts: [{ type: "text", text: ctxText }] },
    })).catch(() => {});
  }
}

export default async function failproofaiPlugin({ client, directory }) {
  return {
    event: async ({ event }) => {
      if (!event || !event.type) return;
      if (event.type === "message.updated") {
        const props = event.properties || {};
        const info = props.info || props.message || {};
        const role = info.role || props.role;
        if (role !== "user") return;
        const sessionID = info.sessionID || info.sessionId || info.session_id || props.sessionID;
        const r = runFailproofai("UserPromptSubmit", {
          session_id: sessionID, cwd: directory, hook_event_name: "UserPromptSubmit",
        }, directory);
        applyDecision(r, { client, sessionID });
        return;
      }
      const claudeEvent = BUS_EVENT_MAP[event.type];
      if (!claudeEvent) return;
      const props = event.properties || {};
      const sessionID = props.sessionID || (props.session && props.session.id) || props.id;
      const r = runFailproofai(claudeEvent, {
        session_id: sessionID, cwd: directory, hook_event_name: claudeEvent,
      }, directory);
      applyDecision(r, { client, sessionID });
    },

    "tool.execute.before": async (input, output) => {
      const r = runFailproofai("PreToolUse", {
        session_id: input.sessionID,
        cwd: directory,
        tool_name: input.tool,
        tool_input: output.args,
        hook_event_name: "PreToolUse",
      }, directory);
      applyDecision(r, { client, sessionID: input.sessionID });
    },

    "tool.execute.after": async (input, output) => {
      const r = runFailproofai("PostToolUse", {
        session_id: input.sessionID,
        cwd: directory,
        tool_name: input.tool,
        tool_input: input.args,
        tool_response: { title: output.title, output: output.output, metadata: output.metadata },
        hook_event_name: "PostToolUse",
      }, directory);
      applyDecision(r, { client, sessionID: input.sessionID });
    },

    "permission.ask": async (input, output) => {
      const r = runFailproofai("PermissionRequest", {
        session_id: input.sessionID,
        cwd: directory,
        tool_name: input.tool || input.command || "permission",
        tool_input: input,
        hook_event_name: "PermissionRequest",
      }, directory);
      try {
        applyDecision(r, { client, sessionID: input.sessionID });
      } catch {
        output.status = "deny";
      }
    },
  };
}
