/**
 * One-off generator for the failproofai CLI startup banner.
 *
 * Reads the wordmark PNG at assets/wordmark/source.png, crops to its
 * non-transparent bounding box, downsamples to a small character grid
 * using a box filter, and emits two pre-rendered banner arrays into
 * scripts/banner.generated.ts:
 *
 *   - coloredBanner: 24-bit ANSI fg/bg per cell, using `▀` (upper-half
 *     block) so each character cell encodes 2 vertically-stacked source
 *     pixels at 1:1 aspect.
 *   - monoBanner: same pixel grid rendered with monochrome Unicode block
 *     chars (▀ ▄ █ space) for terminals where colors are off / NO_COLOR.
 *
 * Re-run when the source logo changes:
 *   bun scripts/generate-banner.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { PNG } from "pngjs";

// Target grid (in character cells). Each cell = 2 vertically-stacked source
// pixels via the ▀ upper-half-block trick, so the source-pixel grid is
// TARGET_COLS × (TARGET_ROWS * 2). Source aspect is ~3.26:1; we honor it
// roughly by choosing rows = round(cols / 3.26 / 2).
const TARGET_COLS = 46;
const TARGET_ROWS = 7;

// Pixel is considered "filled" when alpha is at least this. Anything below
// becomes a transparent cell (no bg) so the banner blends with the user's
// terminal background instead of painting a black box.
const ALPHA_THRESHOLD = 96;

const here = dirname(fileURLToPath(import.meta.url));
const sourcePath = resolve(here, "../assets/wordmark/source.png");
const outPath = resolve(here, "banner.generated.ts");

const png = PNG.sync.read(readFileSync(sourcePath));
const { width: srcW, height: srcH, data } = png;

// Find the non-transparent bounding box so we crop padding before resizing.
let bbLeft = srcW, bbRight = -1, bbTop = srcH, bbBottom = -1;
for (let y = 0; y < srcH; y++) {
  for (let x = 0; x < srcW; x++) {
    const a = data[(y * srcW + x) * 4 + 3];
    if (a >= ALPHA_THRESHOLD) {
      if (x < bbLeft) bbLeft = x;
      if (x > bbRight) bbRight = x;
      if (y < bbTop) bbTop = y;
      if (y > bbBottom) bbBottom = y;
    }
  }
}
if (bbRight < 0) throw new Error("source PNG appears fully transparent");
const cropW = bbRight - bbLeft + 1;
const cropH = bbBottom - bbTop + 1;

// Box-filter downsample: each target pixel = average RGBA over its source
// rectangle. Alpha-weighted RGB averaging avoids halo from transparent
// pixels bleeding into edge cells.
const dstW = TARGET_COLS;
const dstH = TARGET_ROWS * 2;
type Px = { r: number; g: number; b: number; a: number };
const dst: Px[] = new Array(dstW * dstH);
for (let dy = 0; dy < dstH; dy++) {
  const y0 = bbTop + Math.floor((dy * cropH) / dstH);
  const y1 = bbTop + Math.floor(((dy + 1) * cropH) / dstH);
  for (let dx = 0; dx < dstW; dx++) {
    const x0 = bbLeft + Math.floor((dx * cropW) / dstW);
    const x1 = bbLeft + Math.floor(((dx + 1) * cropW) / dstW);
    let rSum = 0, gSum = 0, bSum = 0, aSum = 0, weightSum = 0, count = 0;
    for (let y = y0; y < y1; y++) {
      for (let x = x0; x < x1; x++) {
        const i = (y * srcW + x) * 4;
        const a = data[i + 3];
        rSum += data[i] * a;
        gSum += data[i + 1] * a;
        bSum += data[i + 2] * a;
        aSum += a;
        weightSum += a;
        count++;
      }
    }
    const avgA = count ? Math.round(aSum / count) : 0;
    const px: Px = weightSum > 0
      ? {
          r: Math.round(rSum / weightSum),
          g: Math.round(gSum / weightSum),
          b: Math.round(bSum / weightSum),
          a: avgA,
        }
      : { r: 0, g: 0, b: 0, a: 0 };
    dst[dy * dstW + dx] = px;
  }
}

const ESC = "\x1b[";
const RESET = `${ESC}0m`;
const fg = (p: Px) => `${ESC}38;2;${p.r};${p.g};${p.b}m`;
const bg = (p: Px) => `${ESC}48;2;${p.r};${p.g};${p.b}m`;
const bgDefault = `${ESC}49m`;

const coloredLines: string[] = [];
const monoLines: string[] = [];
for (let row = 0; row < TARGET_ROWS; row++) {
  let colored = "";
  let mono = "";
  for (let col = 0; col < TARGET_COLS; col++) {
    const top = dst[(row * 2) * dstW + col];
    const bot = dst[(row * 2 + 1) * dstW + col];
    const topOn = top.a >= ALPHA_THRESHOLD;
    const botOn = bot.a >= ALPHA_THRESHOLD;
    if (!topOn && !botOn) {
      colored += `${RESET} `;
      mono += " ";
    } else if (topOn && !botOn) {
      colored += `${fg(top)}${bgDefault}▀`;
      mono += "▀";
    } else if (!topOn && botOn) {
      colored += `${fg(bot)}${bgDefault}▄`;
      mono += "▄";
    } else {
      colored += `${fg(top)}${bg(bot)}▀`;
      mono += "█";
    }
  }
  coloredLines.push(colored + RESET);
  monoLines.push(mono.replace(/\s+$/, ""));
}

const header = `// Auto-generated by scripts/generate-banner.ts. Do not edit by hand.
// Source: assets/wordmark/source.png
// Grid: ${TARGET_COLS} cols × ${TARGET_ROWS} rows (= ${TARGET_COLS}×${TARGET_ROWS * 2} source pixels via ▀ half-block).
`;
const fmt = (lines: string[]) =>
  "[\n" + lines.map(l => "  " + JSON.stringify(l)).join(",\n") + ",\n]";

writeFileSync(
  outPath,
  `${header}
export const BANNER_COLS = ${TARGET_COLS};
export const BANNER_ROWS = ${TARGET_ROWS};

export const coloredBanner: string[] = ${fmt(coloredLines)};

export const monoBanner: string[] = ${fmt(monoLines)};
`,
);

console.log(`wrote ${outPath} (${TARGET_COLS}×${TARGET_ROWS}, source bbox ${cropW}×${cropH})`);
